### ISSUE TITLE
video: full knowledge of what we can expect with video playback and time limit for automatic looped playbacl

### ISSUE THREAD

**Issue by rgbk** [FutureCorpLTD/vvatch-holding-page#32]

**Comment by isjackwild** [comment]
uuh the post where i saw this was from 2013... i dunno if it's updated now. i'm sure lots of autoplay videos are longer than 10secs

**Comment by isjackwild** [comment]
Okay, done a few tests, and here's the lowdown I gather:

— When people share the URL, the media won't auto-open, but once opened it will autoplay and loop (click to play on mobile)
— When vvatch shares a GIF, it will autoplay and be in peoples timelines, desktop and mobile
— the url parameter of the tweet isn't needed, if it's left blank it will just add the url of the page which it came from
— if we write vvatch.tv as the text, and share it from vvatch.tv there could duplicate the message. So it's best we leave the url permater blank, and write a custom message ('stop searching start vvatching?), which people can delete and write-over, but the url will stay in their tweet.
