### ISSUE TITLE
Since we have the hamburger and no video card on the info screen

### ISSUE THREAD

**Issue by rgbk** [FutureCorpLTD/vvatch-holding-page#48]
Push the eyes and content up on the page, user can click anywhere to go back. more zen

![image](https://cloud.githubusercontent.com/assets/715901/10326984/f9eddb36-6c99-11e5-9444-9fd2f0d31109.png)

**Comment by rgbk** [comment]
So no hamburger on this screen either, let's try that.

**Comment by isjackwild** [comment]
question mark instead
